SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, sum(S.SALES * B.PRICE) as TOTAL_SALES
from BOOK B
join AUTHOR A
    on B.AUTHOR_ID = A.AUTHOR_ID
join BOOK_SALES S
    on B.BOOK_ID = S.BOOK_ID
where S.SALES_DATE between '2022-01-01' and '2022-01-31'
group by B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
order by B.AUTHOR_ID asc, B.CATEGORY desc;