select extract(YEAR from DIFFERENTIATION_DATE) as YEAR, (max(SIZE_OF_COLONY) over (PARTITION BY EXTRACT(YEAR from DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) as YEAR_DEV, ID
from ECOLI_DATA
order by YEAR asc, YEAR_DEV asc;