SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
from REST_INFO R
WHERE (R.FOOD_TYPE, R.FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
order by R.FOOD_TYPE desc;