SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, A.CONTENTS, A.CREATED_DATE
FROM USED_GOODS_BOARD AS A
JOIN USED_GOODS_REPLY AS B
ON A.BOARD_ID = B.BOARD_ID
WHERE DATE_FORMAT(A.CREATED_DATE, '%y-%m') = '2022-10'
ORDER BY A.CREATED_DATE ASC, A.TITLE ASC