SELECT PARENT.ID, CASE
                    WHEN CHILD.PARENT_ID IS NOT NULL
                    THEN COUNT(*)
                    ELSE 0
                    END AS CHILD_COUNT
FROM ECOLI_DATA AS PARENT
LEFT JOIN ECOLI_DATA AS CHILD
ON PARENT.ID = CHILD.PARENT_ID
GROUP BY PARENT.ID
ORDER BY PARENT.ID