SELECT SUM(HG.SCORE) AS SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES AS HE, HR_GRADE AS HG
WHERE HE.EMP_NO = HG.EMP_NO AND HG.YEAR = 2022
GROUP BY HE.EMP_NO
ORDER BY SCORE DESC LIMIT 1