SELECT UU.USER_ID, UU.NICKNAME, SUM(UB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UB
INNER JOIN USED_GOODS_USER UU
ON UB.WRITER_ID = UU.USER_ID
WHERE UB.STATUS = 'DONE'
GROUP BY UU.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES