SELECT CONCAT('/home/grep/src/', UF.BOARD_ID, '/', 
              UF.FILE_ID, UF.FILE_NAME, UF.FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE UF
JOIN USED_GOODS_BOARD UB
ON UF.BOARD_ID = UB.BOARD_ID
WHERE UB.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY UF.FILE_ID DESC